name: "Build docs"

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs*.yml"
      - ".github/workflows/docs*.yaml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - run: make docs-build
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          force: false
          clean-exclude: |
            pr-preview
